### ISSUE TITLE
Platform not sent in Transcript.

### ISSUE THREAD

**Issue by Sonasi986** [forcedotcom/ServiceSDK-iOS#108]
### Issue description

Hello, when I open a chat in the iOS App every PrechatObject are sent except the Platform.
Acutally the Platform seems to be sent directly by Service SDK. 

On the Android ServiceSDK they have nothing to do and the platform + user agent is correctly sent to Salesforce.
On the iOS ServiceSDK the platform is not sent and the user agent is very strange and different from the Android one.

### Reproduction steps
Simply open the chat on an iOS App.

### Version of SDK components being used
Version 220.1.0 (Using Cocoapods)

### Device(s) and version(s) of iOS being used
iPhone X & XS running iOS 12.0

**Comment by aeisses** [comment]
@Sonasi986 The iOS SDK has an open bug to send the platform value for the iOS SDK.

That is actually a setting when the chat connection starts and not related to prechat. You can make your own platform value and send that value through PreChat. You might need to name it something else.

I am not sure when this will be fixed in the iOS SDK.

Thanks,
Aaron
