### ISSUE TITLE
The search function doesn’t work with Japanese

### ISSUE THREAD

**Issue by ikushige** [forcedotcom/ServiceSDK-iOS#29]
The search function doesn’t work with Japanese, which is happening with ver214.

**Comment by aeisses** [comment]
@ikushige A bug has been opened for this issue.

**Comment by ikushige** [comment]
@aeisses You mean you guys has been working on this issue?  If there is an issue related to it, please share a link  with me to enable to track the progress of implementation from our side.

**Comment by aeisses** [comment]
@ikushige Sorry for the slow response I was away. We have issues a patch release fixing this issue:
https://developer.salesforce.com/page/SnapinsMobile

The patch that fixes this issue is 214.0.1. We have also issues a patch for another upgrade crash in 214.0.2. 214.0.2 will also have the fix for this issue.

Thanks,
Aaron
