### ISSUE TITLE
SCServiceCloudDelegate not called

### ISSUE THREAD

**Issue by fermoya** [forcedotcom/ServiceSDK-iOS#6]
Hi,

I'm using the last version of this SDK to add to my project a live agent. I have the following frameworks embedded:
* CocoaLumberjack
* SalesforceAnalytics
* SalesforceSDKCore
* SmartStore
* ServiceCore
* ServiceChat

By using "SCServiceCloudDelegate" and configuring the chat presentation as "SCSChatPresentationStyleFullscreen", I pretend to change the modal presentation style to "formSheet". For that I wanna use the delegate method "serviceCloud: willDisplayViewController: animated:" Nonetheless, this method, as long as "serviceCloud: didDisplayViewController: animated:" aren't called by the SDK. The rest of them are called but have no use for me.

I've tried with later versions and these methods are called as expected but I need the latest version in my project.

Regards

**Comment by sfyz** [comment]
I'll check in with developers about this problem. Can you tell me what version of the SDK you are using that experiences this problem? Also, I'm not sure I understood that last sentence... are you saying that a later version fixes the problem?

**Comment by fermoya** [comment]
Hi, 

Sorry I meant to say "I've tried with **older** versions...". Now i'm trying with your latest version, "208.6.0". I donwloaded some time ago your sample project "HelloLiveAgent". With that one it works perfectly, I'm attaching it. The thing is I have to use the latest one so I support iOS 11, you've fixed some issues there.

Regards

[HelloLiveAgentChat.zip](https://github.com/forcedotcom/ServiceSDK-iOS/files/1358867/HelloLiveAgentChat.zip)

**Comment by sfyz** [comment]
OK. Thanks for the info. I filed a ticket for the developers to look into. Will follow up.

**Comment by MikeNachbaur** [comment]
Hello @fermoya, I have indeed been able to reproduce this in our latest release as well.  It's very unfortunate and we're investigating this now.

My recommendation though is to use the `serviceCloud:transitioningDelegateForPresentedController:presentingController:` delegate method instead of the `willDisplay` method.  This is more suited to customizing the presentation style of a view controller.

You can return `nil` so as to avoid using the built-in presentation controllers, and can at that time change the presentedController's modal presentation style.  The important thing is that this method is invoked _before_ the animated presentation begins, and would be a much more reliable way for you to customize the appearance of the modal view controllers.

I hope that helps!

**Comment by sfyz** [comment]
Also, the issue with ServiceCloudDelegate methods not getting called should be fixed in the next release.

**Comment by tmyrden** [comment]
@fermoya Our latest release is now out, this issue should be fixed for you! 😃 

[October 2017 Release](https://github.com/forcedotcom/ServiceSDK-iOS/releases/tag/210.0)
