### ISSUE TITLE
iOS Push notifications have stopped working

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/ServiceSDK-iOS#86]
### Issue description
We can't receive push notification for all the cases logged by all the users. It was working before but the functionality had stopped.

EXPECTED RESULT/UX
I should receive a Push Notification within seconds, for the auto-response to the case I just opened

ACTUAL RESULT/UX (bug)
I do NOT receive a Push Notification at all, for the auto-response to the case I just opened

### Reproduction steps
I open the iOS app (any version)
I authenticate as a new user or an existing user
Press "Get in touch” button from More screen
I open a new case and fill in all mandatory fields
Click Submit
*** No push notification received****

### Version of SDK components being used
All SDK version

### Device(s) and version(s) of iOS being used
iOS 11.0 and above

### Screenshots / Videos

[Video.zip](https://github.com/forcedotcom/ServiceSDK-iOS/files/3255319/Video.zip)

**Comment by shanecinense1994** [comment]
Hi,

Is there any update for this?
Note that this is an urgent case on our end as we will be having a PROD deployment on 11th June and  this issue may block our release.
Kindly take a look on this ticket as a priority.

Thank you

Regards,
Shane

**Comment by aeisses** [comment]
Hey geekandt and shanecinense1994,

We are looking into this issue. We will get back to you when we know more information.

Aaron

**Comment by shanecinense1994** [comment]
Thanks @aeisses we'll await for your update.

**Comment by aeisses** [comment]
@shanecinense1994 and @geekandt,

Push notification issues are tough on the mobile side. You need to open a case with our main support line. The issue is probably with the APEX trigger on the server, the mobile team has no visibility to the APEX triggers.

If you want to get a resolution you need to open a support case: https://help.salesforce.com/home.

Sorry this is taking so long, but it is WWDC week and a lot is going on.

Thanks,
Aaron
