### ISSUE TITLE
Error while submitting to AppStore - Signing issue

### ISSUE THREAD

**Issue by ohadis1** [forcedotcom/ServiceSDK-iOS#92]
I'm using ServiceSDK/SOS version 212.0.4  pod but I couldn't upload the ipa to store.

I use:
Xcode 10.2.1
CoccoaPods 1.7.2
Deployment Target is 9 (so I couldn't use the latest SOS version).

I have added the Run Script as described here: https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/prepare_for_appstore.htm

While uploading to AppStore I get this error:

ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [*.app/Frameworks/ServiceCore.framework/prepare-framework--] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"

Thanks.

**Comment by MikeNachbaur** [comment]
It appears that the `prepare-framework` script is either not being properly removed by itself, or something else is introducing a new file. It appears that the filename `prepare-framework--` is what the App Store is complaining about, but that file isn't included in our distribution.

Can you verify that something within your environment isn't accidentally duplicating the `prepare-framework` file? That seems to be the root-cause, since the `prepare-framework` script's purpose is to both a) strip out simulator artifacts, and b) remove itself from the resulting build product so the AppStore doesn't thing a command-line script is included.

**Comment by aeisses** [comment]
Without more information or communication from the user this ticket can not move any further, closing.
